<script>
export default {
  name: "exercises-list",
  emits: ['update-exercise', 'create-exercise'],
  data() {
    return {
      exercise: null,
      searchTerm: '',
      currentPage: 0,
      rowsPerPage: 6,
    }
  },
  props: {
    exercises: {
      type: Array,
      required: true,
    }
  },
  computed: {
    filteredExercises() {
      if (!this.searchTerm) {
        return this.exercises;
      }

      const lowerCaseSearchTerm = this.searchTerm.toLowerCase();
      return this.exercises.filter(exercise => {
        const exerciseName = exercise.name ? String(exercise.name).toLowerCase() : '';
        return exerciseName.includes(lowerCaseSearchTerm);
      });
    },
    paginatedExercises() {
      const start = this.currentPage * this.rowsPerPage;
      const end = start + this.rowsPerPage;
      return this.filteredExercises.slice(start, end);
    }
  },
  methods: {
    onUpdateExercise(exercise) {
      console.log('Update exercise:', exercise);
      this.$emit('update-exercise', exercise);
    },
    onPageChange(event) {
      this.currentPage = event.page;
    },
    onCreateExercise() {
      this.$emit('create-exercise');  // Emite evento para que el padre lo abra
    }
  }
}
</script>

<template>
  <div class="grid">
    <div class="col-12 text-center">
      <h2 class="text-3xl font-bold mb-4">Exercises</h2>
    </div>

    <div class="col-12 mb-4 flex justify-content-center">
      <pv-icon-field class="p-input-icon-left w-full md:w-8 lg:w-6">
        <pv-input-icon class="pi pi-search"></pv-input-icon>
        <pv-input-text v-model="searchTerm" placeholder="Search exercises by name..." class="w-full" />
      </pv-icon-field>

      <pv-button label="Nuevo Ejercicio" icon="pi pi-plus" class="ml-3" @click="onCreateExercise" />
    </div>

    <div v-for="exercise in paginatedExercises" :key="exercise.id" class="col-12 md:col-6 lg:col-4 flex justify-content-center">
      <pv-card class="exercise-card w-full">
        <template #title>{{ exercise.name }}</template>
        <template #subtitle>{{ exercise.description }}</template>
        <template #content>
          <div class="card-image-wrapper">
            <pv-image v-if="exercise.imageUri" :src="exercise.imageUri" :alt="exercise.name"
                      class="exercise-card-image" preview />
          </div>
        </template>
        <template #footer>
          <pv-button label="Update" icon="pi pi-pencil" class="p-button-sm" @click="onUpdateExercise(exercise)" />
        </template>
      </pv-card>
    </div>

    <div class="col-12 flex justify-content-center mt-4">
      <pv-paginator :rows="rowsPerPage"
                    :totalRecords="filteredExercises.length"
                    :first="currentPage * rowsPerPage"
                    @page="onPageChange" />
    </div>
  </div>
</template>

<style scoped>
.exercise-card {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
  transition: transform 0.2s ease, box-shadow 0.2s ease;
  display: flex;
  flex-direction: column;
  max-width: 100%;
  box-sizing: border-box;
}

.exercise-card .p-card-content {
  flex-grow: 1;
  padding: 0 1.25rem 0.5rem;
  display: flex;
  justify-content: center;
  align-items: center;
  overflow: hidden;
}

.card-image-wrapper {
  width: 100%;
  /* NO fixed height here */
  display: flex;
  justify-content: center;
  align-items: center;
  overflow: hidden;
  min-height: 100px; /* Optional: Consistent min-height */
}

/* Target the actual <img> element generated by pv-image using ::v-deep */
.exercise-card-image ::v-deep(img) {
  width: 100%;
  height: auto;
  object-fit: contain; /* CRUCIAL: Ensures the entire image is visible */
  display: block;
  border-radius: 0.25rem;
}
</style>