<script>
export default {
  name: "meals-list",
  emits: ['update-meal', 'create-meal'],
  data() {
    return {
      meal: null,
      searchTerm: '',
      currentPage: 0,
      rowsPerPage: 6,
    }
  },
  props: {
    meals: {
      type: Array,
      required: true,
    }
  },
  computed: {
    filteredMeals() {
      if (!this.searchTerm) {
        return this.meals;
      }

      const lowerCaseSearchTerm = this.searchTerm.toLowerCase();
      return this.meals.filter(meal => {
        // Asegúrate que meal.name existe y es un string antes de intentar toLowerCase()
        const mealName = meal.name ? String(meal.name).toLowerCase() : '';
        return mealName.includes(lowerCaseSearchTerm);
      });
    },
    paginatedMeals() {
      const start = this.currentPage * this.rowsPerPage;
      const end = start + this.rowsPerPage;
      return this.filteredMeals.slice(start, end);
    }
  },
  methods: {
    onUpdateMeal(meal) {
      console.log('Update meal:', meal);
      this.$emit('update-meal', meal);
    },
    onPageChange(event) {
      this.currentPage = event.page;
    },
    onCreateMeal() {
      this.$emit('create-meal');
    }
  },
}
</script>

<template>
  <div class="grid">
    <div class="col-12 text-center">
      <h2 class="text-3xl font-bold mb-4">Meals</h2>
    </div>

    <div class="col-12 mb-4 flex justify-content-center">
      <pv-icon-field class="p-input-icon-left w-full md:w-8 lg:w-6">
        <pv-input-icon class="pi pi-search"></pv-input-icon>
        <pv-input-text v-model="searchTerm" placeholder="Search meals by name..." class="w-full" />
      </pv-icon-field>

      <pv-button label="Nueva Comida" icon="pi pi-plus" class="ml-3" @click="onCreateMeal" />
    </div>

    <div v-for="meal in paginatedMeals" :key="meal.id" class="col-12 md:col-6 lg:col-4 flex justify-content-center">
      <pv-card class="meal-card w-full">
        <template #title>{{ meal.name }}</template>
        <template #subtitle>{{ meal.description }}</template>
        <template #content>
          <div class="card-image-wrapper">
            <pv-image v-if="meal.imageUri" :src="meal.imageUri" :alt="meal.name"
                      class="meal-card-image" preview />
          </div>
        </template>
        <template #footer>
          <pv-button label="Update" icon="pi pi-pencil" class="p-button-sm" @click="onUpdateMeal(meal)" />
        </template>
      </pv-card>
    </div>

    <div class="col-12 flex justify-content-center mt-4">
      <pv-paginator :rows="rowsPerPage"
                    :totalRecords="filteredMeals.length"
                    :first="currentPage * rowsPerPage"
                    @page="onPageChange" />
    </div>
  </div>
</template>

<style scoped>
.meal-card {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
  transition: transform 0.2s ease, box-shadow 0.2s ease;
  display: flex;
  flex-direction: column;
  max-width: 100%;
  box-sizing: border-box;
}

/* Ensure the content area grows to push the footer down */
.meal-card .p-card-content {
  flex-grow: 1;
  padding: 0 1.25rem; /* Adjust horizontal padding to match design */
  padding-bottom: 0.5rem; /* Small bottom padding if needed */
  display: flex;       /* Use flexbox to center content */
  justify-content: center; /* Center horizontally */
  align-items: center;     /* Center vertically */
  overflow: hidden; /* Just in case, to prevent any text/image overflow from here */
}

.card-image-wrapper {
  width: 100%; /* Image wrapper takes full width of card content */
  /* NO fixed height here. Let the image define the height. */
  display: flex; /* Use flex to center the image within the wrapper */
  justify-content: center;
  align-items: center;
  overflow: hidden; /* Important: Ensures image doesn't overflow this container */
  min-height: 100px; /* Optional: Give a minimum height so cards don't collapse for missing/tiny images */
  /* You could also set a max-height here if you want to cap the image height,
     which would then reintroduce letterboxing for taller images.
     For "imagen completa" and "adaptarse dinamicamente", it's usually best to omit max-height initially. */
}

/* Target the actual <img> element generated by pv-image using ::v-deep */
.meal-card-image ::v-deep(img) {
  width: 100%;       /* Image takes full width of its wrapper */
  height: auto;      /* Maintain aspect ratio automatically */
  object-fit: contain; /* CRUCIAL: Ensures the entire image is visible, scaling down if necessary.
                          This will introduce blank space (letterboxing/pillarboxing) if the image's
                          aspect ratio doesn't match the wrapper's aspect ratio, but it will show the
                          COMPLETE image. */
  display: block;    /* Remove any extra space below the image */
  border-radius: 0.25rem; /* Apply rounded corners to the image */
}

/* NEW: Styles for the search input and its icon */
.p-input-icon-left {
  position: relative;
  display: inline-flex; /* Ensures the span behaves like a flexbox for alignment */
  align-items: center; /* Centers the icon vertically */
}

.p-input-icon-left > i {
  position: absolute;
  left: 0.75rem; /* Adjust icon position from the left */
  z-index: 1; /* Ensure icon is above the input text */
}

.p-input-icon-left > .p-inputtext {
  padding-left: 2.5rem; /* Ensure enough padding for the icon */
}
</style>